services:
  api:
    build: .
    ports:
      - ${API_PORT}:8089
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8089

  db:
    image: pgvector/pgvector:pg13
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y locales &&
        sed -i -e 's/# pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen &&
        locale-gen &&
        update-locale LANG=pt_BR.UTF-8 &&
        /usr/local/bin/docker-entrypoint.sh postgres
      "
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      LANG: pt_BR.UTF-8
      LC_COLLATE: pt_BR.UTF-8
      LC_CTYPE: pt_BR.UTF-8
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 30s
      retries: 5
      start_period: 5s
      timeout: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres_data: